[build-options]
  observabilityIncluded = true

[package]
  distribution = "2201.3.1"
  export = ["json_to_json_transformation"]
  icon = "docs/icon.png"
  keywords = ["Kind/Sample","Type/Service","Category/Service","Internal/http"]
  name = "json_to_json_transformation"
  org = "puneetinc"
  version = "3.1.1"

